name: My First Workflow


on: push

jobs:
    first_name:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout To Repository
              uses: actions/checkout@v4

            - name: Welcome Message
              run: echo "Hello World"

            - name: List_Files
              run: |
                  ls
                  ls -la
                  ifconfig
                  ping google.com -c 4


            - name: IP Adderess
              run: hostname -I

            - name: Cat command to README
              run: cat README.md

            - name: Generate ASCII Artwork With cowsay
              run: cowsay -f dragon "DracarysSSSSSSSS" > dragon.txt