name: My First Workflow


on: push

jobs:
    first_name:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout To Repository
              uses: actions/checkout@v4

            - name: Welcome Message
              run: echo "Hello World"

            - name: List_Files
              run: ls

            - name: IP Adderess
              run: hostname -I