name: third party package

on: push

jobs:
  cowsay_package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project repo
      uses: actions/checkout@v4

    - name: Check files in the dir
      run: ls -ltra

    - name: change permission to execute script
      run: chmod +x ascii-script.sh

    - name: executing shell sccript
      run: ./ascii-script.sh