name: third party package installation

on:
  push:
    branches: [new-1]

jobs:
  cowsay_package:
    runs-on: ubuntu-latest
    steps:
    - name: update
      run: sudo apt update
    - name: install cowsay package
      run: sudo apt install cowsay
    - name: Generate ASCII Artwork With cowsay
      run: cowsay -f dragon "DracarysSSSSSSSS" > dragon.txt
    - name: See ASCII art
      run: cat dragon.txt